//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/3/AircraftControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AircraftControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AircraftControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AircraftControls"",
    ""maps"": [
        {
            ""name"": ""Aircraft"",
            ""id"": ""da686d82-dc10-45e7-bef9-dc0d31a24f5f"",
            ""actions"": [
                {
                    ""name"": ""ThrottleUp"",
                    ""type"": ""Value"",
                    ""id"": ""0cd01a71-9931-4b1f-bc51-5e0e54a2e663"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThrottleDown"",
                    ""type"": ""Value"",
                    ""id"": ""c1347297-5d99-4780-9ff7-16a07de02fe3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PitchUp"",
                    ""type"": ""Value"",
                    ""id"": ""938fbd98-2976-4a3c-8bc8-8aaba7d174fb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PitchDown"",
                    ""type"": ""Value"",
                    ""id"": ""2d81b114-9040-4284-b982-c8f05a465505"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollLeft"",
                    ""type"": ""Value"",
                    ""id"": ""62a2ea81-e3b1-478b-89a6-fca2b9b390b3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollRight"",
                    ""type"": ""Value"",
                    ""id"": ""7a6006a1-8032-4072-9374-e4a787cdcafd"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawLeft"",
                    ""type"": ""Value"",
                    ""id"": ""ebc0691e-227a-4cc1-aa07-feffcc2eb9f7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawRight"",
                    ""type"": ""Value"",
                    ""id"": ""5fdebb51-807e-4825-aa2e-3a9d7fdd0303"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleAB"",
                    ""type"": ""Button"",
                    ""id"": ""3ab256be-7d5c-4d3e-b443-dff2d830bf75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldAttribute"",
                    ""type"": ""Button"",
                    ""id"": ""c2267792-c8ef-4576-9ac9-7ac42302b0f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""833cb2d8-899a-4433-975d-7ca135eaa514"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b74395c8-5140-42d9-9ce3-b62aa6a3bb55"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""975a4d7a-1b07-41d9-a3eb-650e8d20b60f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fac72156-d629-4ead-a115-6376bb1d75b2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b92ba66-be8f-403e-906b-e3970e1838f0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd936f93-796f-4924-b5b0-d9a2bc5add42"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7bea47c-5598-4c43-99b8-2fa800e07764"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb975086-70ee-4153-8faf-66b3b66cdda8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e60aee23-b959-4df4-ab6e-01604f404176"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleAB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d53f7051-8444-4520-a31b-04d01db698e7"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldAttribute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Aircraft
        m_Aircraft = asset.FindActionMap("Aircraft", throwIfNotFound: true);
        m_Aircraft_ThrottleUp = m_Aircraft.FindAction("ThrottleUp", throwIfNotFound: true);
        m_Aircraft_ThrottleDown = m_Aircraft.FindAction("ThrottleDown", throwIfNotFound: true);
        m_Aircraft_PitchUp = m_Aircraft.FindAction("PitchUp", throwIfNotFound: true);
        m_Aircraft_PitchDown = m_Aircraft.FindAction("PitchDown", throwIfNotFound: true);
        m_Aircraft_RollLeft = m_Aircraft.FindAction("RollLeft", throwIfNotFound: true);
        m_Aircraft_RollRight = m_Aircraft.FindAction("RollRight", throwIfNotFound: true);
        m_Aircraft_YawLeft = m_Aircraft.FindAction("YawLeft", throwIfNotFound: true);
        m_Aircraft_YawRight = m_Aircraft.FindAction("YawRight", throwIfNotFound: true);
        m_Aircraft_ToggleAB = m_Aircraft.FindAction("ToggleAB", throwIfNotFound: true);
        m_Aircraft_HoldAttribute = m_Aircraft.FindAction("HoldAttribute", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Aircraft
    private readonly InputActionMap m_Aircraft;
    private List<IAircraftActions> m_AircraftActionsCallbackInterfaces = new List<IAircraftActions>();
    private readonly InputAction m_Aircraft_ThrottleUp;
    private readonly InputAction m_Aircraft_ThrottleDown;
    private readonly InputAction m_Aircraft_PitchUp;
    private readonly InputAction m_Aircraft_PitchDown;
    private readonly InputAction m_Aircraft_RollLeft;
    private readonly InputAction m_Aircraft_RollRight;
    private readonly InputAction m_Aircraft_YawLeft;
    private readonly InputAction m_Aircraft_YawRight;
    private readonly InputAction m_Aircraft_ToggleAB;
    private readonly InputAction m_Aircraft_HoldAttribute;
    public struct AircraftActions
    {
        private @AircraftControls m_Wrapper;
        public AircraftActions(@AircraftControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ThrottleUp => m_Wrapper.m_Aircraft_ThrottleUp;
        public InputAction @ThrottleDown => m_Wrapper.m_Aircraft_ThrottleDown;
        public InputAction @PitchUp => m_Wrapper.m_Aircraft_PitchUp;
        public InputAction @PitchDown => m_Wrapper.m_Aircraft_PitchDown;
        public InputAction @RollLeft => m_Wrapper.m_Aircraft_RollLeft;
        public InputAction @RollRight => m_Wrapper.m_Aircraft_RollRight;
        public InputAction @YawLeft => m_Wrapper.m_Aircraft_YawLeft;
        public InputAction @YawRight => m_Wrapper.m_Aircraft_YawRight;
        public InputAction @ToggleAB => m_Wrapper.m_Aircraft_ToggleAB;
        public InputAction @HoldAttribute => m_Wrapper.m_Aircraft_HoldAttribute;
        public InputActionMap Get() { return m_Wrapper.m_Aircraft; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AircraftActions set) { return set.Get(); }
        public void AddCallbacks(IAircraftActions instance)
        {
            if (instance == null || m_Wrapper.m_AircraftActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AircraftActionsCallbackInterfaces.Add(instance);
            @ThrottleUp.started += instance.OnThrottleUp;
            @ThrottleUp.performed += instance.OnThrottleUp;
            @ThrottleUp.canceled += instance.OnThrottleUp;
            @ThrottleDown.started += instance.OnThrottleDown;
            @ThrottleDown.performed += instance.OnThrottleDown;
            @ThrottleDown.canceled += instance.OnThrottleDown;
            @PitchUp.started += instance.OnPitchUp;
            @PitchUp.performed += instance.OnPitchUp;
            @PitchUp.canceled += instance.OnPitchUp;
            @PitchDown.started += instance.OnPitchDown;
            @PitchDown.performed += instance.OnPitchDown;
            @PitchDown.canceled += instance.OnPitchDown;
            @RollLeft.started += instance.OnRollLeft;
            @RollLeft.performed += instance.OnRollLeft;
            @RollLeft.canceled += instance.OnRollLeft;
            @RollRight.started += instance.OnRollRight;
            @RollRight.performed += instance.OnRollRight;
            @RollRight.canceled += instance.OnRollRight;
            @YawLeft.started += instance.OnYawLeft;
            @YawLeft.performed += instance.OnYawLeft;
            @YawLeft.canceled += instance.OnYawLeft;
            @YawRight.started += instance.OnYawRight;
            @YawRight.performed += instance.OnYawRight;
            @YawRight.canceled += instance.OnYawRight;
            @ToggleAB.started += instance.OnToggleAB;
            @ToggleAB.performed += instance.OnToggleAB;
            @ToggleAB.canceled += instance.OnToggleAB;
            @HoldAttribute.started += instance.OnHoldAttribute;
            @HoldAttribute.performed += instance.OnHoldAttribute;
            @HoldAttribute.canceled += instance.OnHoldAttribute;
        }

        private void UnregisterCallbacks(IAircraftActions instance)
        {
            @ThrottleUp.started -= instance.OnThrottleUp;
            @ThrottleUp.performed -= instance.OnThrottleUp;
            @ThrottleUp.canceled -= instance.OnThrottleUp;
            @ThrottleDown.started -= instance.OnThrottleDown;
            @ThrottleDown.performed -= instance.OnThrottleDown;
            @ThrottleDown.canceled -= instance.OnThrottleDown;
            @PitchUp.started -= instance.OnPitchUp;
            @PitchUp.performed -= instance.OnPitchUp;
            @PitchUp.canceled -= instance.OnPitchUp;
            @PitchDown.started -= instance.OnPitchDown;
            @PitchDown.performed -= instance.OnPitchDown;
            @PitchDown.canceled -= instance.OnPitchDown;
            @RollLeft.started -= instance.OnRollLeft;
            @RollLeft.performed -= instance.OnRollLeft;
            @RollLeft.canceled -= instance.OnRollLeft;
            @RollRight.started -= instance.OnRollRight;
            @RollRight.performed -= instance.OnRollRight;
            @RollRight.canceled -= instance.OnRollRight;
            @YawLeft.started -= instance.OnYawLeft;
            @YawLeft.performed -= instance.OnYawLeft;
            @YawLeft.canceled -= instance.OnYawLeft;
            @YawRight.started -= instance.OnYawRight;
            @YawRight.performed -= instance.OnYawRight;
            @YawRight.canceled -= instance.OnYawRight;
            @ToggleAB.started -= instance.OnToggleAB;
            @ToggleAB.performed -= instance.OnToggleAB;
            @ToggleAB.canceled -= instance.OnToggleAB;
            @HoldAttribute.started -= instance.OnHoldAttribute;
            @HoldAttribute.performed -= instance.OnHoldAttribute;
            @HoldAttribute.canceled -= instance.OnHoldAttribute;
        }

        public void RemoveCallbacks(IAircraftActions instance)
        {
            if (m_Wrapper.m_AircraftActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAircraftActions instance)
        {
            foreach (var item in m_Wrapper.m_AircraftActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AircraftActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AircraftActions @Aircraft => new AircraftActions(this);
    public interface IAircraftActions
    {
        void OnThrottleUp(InputAction.CallbackContext context);
        void OnThrottleDown(InputAction.CallbackContext context);
        void OnPitchUp(InputAction.CallbackContext context);
        void OnPitchDown(InputAction.CallbackContext context);
        void OnRollLeft(InputAction.CallbackContext context);
        void OnRollRight(InputAction.CallbackContext context);
        void OnYawLeft(InputAction.CallbackContext context);
        void OnYawRight(InputAction.CallbackContext context);
        void OnToggleAB(InputAction.CallbackContext context);
        void OnHoldAttribute(InputAction.CallbackContext context);
    }
}
